# NOTE: Do not include leading or trailing slashes in the
# subdirectory.
subdirectory = ""

host = "localhost"
port = 6543
scheme = "http"
session_factory = "todo_add_a_secret"

# https://github.com/python-cas/python-cas
[casclient]
version = "3"
server_url = "https://django-cas-ng-demo-server.herokuapp.com/cas/"

[micro_services.permissions]
url = "https://your.endpoint.here/"
token = "todo_add_a_secret"

[micro_services.permissions.map]
appointments = "appointments"
appointments_lite = "lite"
data_entry = "dentry"
events = "events"
file_archive = "files"
residents = "res"
search_patients = "search"
sysadmin = "sysadmin"
system_status = "status"
