# NOTE: Do not include leading or trailing slashes in the
# subdirectory.
subdirectory = ""

host = "localhost"
port = 6544
scheme = "http"
session_factory = "todo_add_a_secret"


[developer]
auto_login = true
username = "admin"


# https://github.com/python-cas/python-cas
[casclient]
version = "3"
server_url = "https://django-cas-ng-demo-server.herokuapp.com/cas/"


[micro_services.permissions]
url = "https://your.endpoint.here/"
token = "todo_add_a_secret"
mode = "testing" # testing, legacy, else standard
