host = "localhost"
port = 6543
scheme = "http"
home_path = ""
session_factory = "todo_add_a_secret"

# https://github.com/python-cas/python-cas
[casclient]
version = "3"
server_url = "https://django-cas-ng-demo-server.herokuapp.com/cas/"
